# Generated by Django 4.0 on 2022-02-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passwords',
        ),
    ]
