# Generated by Django 4.0 on 2022-02-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('python1', '0002_delete_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='thekoushikdurgas@gmail.com', max_length=254)),
                ('link', models.URLField(default='google.com')),
                ('username', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('subject', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('password', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'passwordlist',
            },
        ),
    ]
