# Generated by Django 4.0 on 2022-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0005_mydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='myservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('name', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('desc', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myserviceslist',
            },
        ),
    ]
