# Generated by Django 4.0 on 2022-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0008_mylanguage_deg_mylanguage_degl_mylanguage_degr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('title1', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('icon', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('link', models.URLField(default='http://google.com')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sociallist',
            },
        ),
    ]
