# Generated by Django 4.0 on 2022-03-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0009_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='myproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('name', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('category', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('desc', models.CharField(default='thekoushikdurgas', max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myprojectlist',
            },
        ),
    ]
