# Generated by Django 4.0 on 2022-03-01 21:38

from django.db import migrations, models
import python1.models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0010_myproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='myprojectpic',
            field=models.ImageField(blank=True, default='customer/pic/default.jpg', null=True, upload_to=python1.models.myprojectpath),
        ),
    ]
