# Generated by Django 4.0 on 2022-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0011_myproject_myprojectpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='category',
            field=models.CharField(choices=[['all', 'All'], ['software', 'software'], ['website', 'website'], ['project', 'project']], default='all', max_length=150),
        ),
    ]
