# Generated by Django 4.0 on 2022-03-03 18:39

from django.db import migrations, models
import python1.models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0012_alter_myproject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='myfriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='thekoushikdurgas', max_length=200)),
                ('myprojectpic', models.ImageField(blank=True, default='myfriend/default.jpg', null=True, upload_to=python1.models.myfriendpath)),
                ('facebook', models.URLField(default='https://www.facebook.com/')),
                ('twitter', models.URLField(default='https://twitter.com/')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/')),
                ('instagram', models.URLField(default='https://www.instagram.com/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myfriendlist',
            },
        ),
        migrations.AlterField(
            model_name='myproject',
            name='myprojectpic',
            field=models.ImageField(blank=True, default='myproject/default.jpg', null=True, upload_to=python1.models.myprojectpath),
        ),
    ]
