# Generated by Django 4.0.3 on 2022-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0013_myfriend_alter_myproject_myprojectpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='category',
            field=models.CharField(choices=[['software', 'software'], ['website', 'website'], ['project', 'project'], ['game', 'game'], ['list', 'list']], default='all', max_length=150),
        ),
    ]
