# Generated by Django 4.0.3 on 2022-03-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0016_mymusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymusic',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
