# Generated by Django 4.0.3 on 2022-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0017_mymusic_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymusic',
            name='audio_link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
