# Generated by Django 4.0.3 on 2022-03-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0019_remove_mymusic_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymusic',
            name='language',
            field=models.CharField(choices=[['hindi', 'hindi'], ['bengali', 'bengali'], ['english', 'english']], default='bengali', max_length=150),
        ),
        migrations.AddField(
            model_name='mymusic',
            name='typeaudio',
            field=models.CharField(choices=[['music', 'music'], ['story', 'story']], default='music', max_length=150),
        ),
    ]
