# Generated by Django 4.0.3 on 2022-03-21 18:27

from django.db import migrations, models
import python1.models


class Migration(migrations.Migration):

    dependencies = [
        ('python1', '0020_mymusic_language_mymusic_typeaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymusic',
            name='audio_file',
            field=models.FileField(blank=True, default='mymusic/audio/default.mp3', max_length=2000, null=True, upload_to=python1.models.mymusicpath2),
        ),
        migrations.AlterField(
            model_name='mymusic',
            name='image',
            field=models.ImageField(blank=True, default='mymusic/pic/default.jpg', max_length=2000, null=True, upload_to=python1.models.mymusicpath1),
        ),
    ]
